### ISSUE TITLE
how to define input as string

### ISSUE THREAD

**Issue by webchaz** [rtfpessoa/diff2html-cli#20]
Is there a way to define the input as two strings as oppose to two files?

**Comment by rtfpessoa** [comment]
Currently there is no way to do this, since we only invoke git directly. 

And the feature it self seems out of context for the purpose of this project.

Still, you can probably use [diff](https://www.npmjs.com/package/diff)'s method `JsDiff.createTwoFilesPatch(oldFileName, newFileName, oldStr, newStr, oldHeader, newHeader)` and then feed it to diff2html, but I am not 100% sure.
