### ISSUE TITLE
ignore package-lock.json

### ISSUE THREAD

**Issue by whyboris** [rtfpessoa/diff2html-cli#36]
## Problem
`package-lock.json` routinely has more than 2000 changes after `npm install` in a large project. 

## Solution
Simply exclude `package-lock.json` from showing up in the _diff_. Optionally give users an option to include it if this behavior is desired.

**Comment by rtfpessoa** [comment]
This project uses yarn so instead of `npm install` you should do `yarn`.

Still if you want to ignore that file feel free to send a PR.

**Comment by whyboris** [comment]
Thank you for the quick response. Sorry if I've described the scenario poorly.

When using _diff2thtml-cli_ on (for example) an Angular project where _package.json_ was recently updated and `npm install` was run, _diff2html-cli_ *correctly* shows the diff between the old and the updated _package-lock.json_ files. 

The problem arises that it's a large file with changes that are useless to (I assume pretty much) any developer. If it was collapsed by default in the HTML view that would be great (but that would require extra functionality to be added to the _diff2html-cli_ & it would still slow down the experience - having to write and possibly render all the contents). The other option is that _diff2html-cli_ simply ignores the file when creating the html diff view.

I am open to creating a PR to implement this feature (provided I find enough time and figure out how to do it). I certainly would want to confirm with you before working on this (fore me) time-consuming task that it would be a welcome _improvement_ to the _diff2html-cli_ rather than an unacceptable change.

Cheers!

**Comment by rtfpessoa** [comment]
Ok I think I got it.

I do not think removing any files by default it a good idea since some people might want to see them.

Still I can see two solutions for your problem. The quickest is excluding the files you want in the diff like this `git diff -- . ':(exclude)package-lock.json' | diff2html -i stdin`. The other would be like you described collapsing files with a lot of lines changed and that would be a nice feature.

If you think you would be willing to implement the second here are some ideas:
* First you could tag the huge files with some class in here https://github.com/rtfpessoa/diff2html/blob/master/src/templates/line-by-line-file-diff.mustache and here https://github.com/rtfpessoa/diff2html/blob/master/src/templates/side-by-side-file-diff.mustache
* Then you could do some JS like this https://github.com/rtfpessoa/diff2html/blob/master/src/ui/js/diff2html-ui.js#L52 to hide them.
* To finish add a button to open the file close to the initial class.

**Comment by alamothe** [comment]
It would be great to collapse huge files, and only load them on user click

`diff2html` can hang for minutes for files which are over 10k lines

**Comment by rtfpessoa** [comment]
Any PRs are welcome.
